// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1Ewd-mAHpCP8xjF0SZoZLGwqDxLN3wc',
    appId: '1:431132444760:web:3732db4a9a367f4f1aa22d',
    messagingSenderId: '431132444760',
    projectId: 'maize-beta-6e103',
    authDomain: 'maize-beta-6e103.firebaseapp.com',
    storageBucket: 'maize-beta-6e103.appspot.com',
    measurementId: 'G-KJVETCHMB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcC2kfJjLQURThNy9EbHsl14rsEB1GuGI',
    appId: '1:431132444760:android:77284446e33cb5061aa22d',
    messagingSenderId: '431132444760',
    projectId: 'maize-beta-6e103',
    storageBucket: 'maize-beta-6e103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPGks_o6vjcWGXQCQtBvp1jANTUVZQfM',
    appId: '1:431132444760:ios:1e7732d1c5b0b5281aa22d',
    messagingSenderId: '431132444760',
    projectId: 'maize-beta-6e103',
    storageBucket: 'maize-beta-6e103.appspot.com',
    iosBundleId: 'com.example.maizeBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPGks_o6vjcWGXQCQtBvp1jANTUVZQfM',
    appId: '1:431132444760:ios:1e7732d1c5b0b5281aa22d',
    messagingSenderId: '431132444760',
    projectId: 'maize-beta-6e103',
    storageBucket: 'maize-beta-6e103.appspot.com',
    iosBundleId: 'com.example.maizeBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo1Ewd-mAHpCP8xjF0SZoZLGwqDxLN3wc',
    appId: '1:431132444760:web:7e09b3094d9d3da11aa22d',
    messagingSenderId: '431132444760',
    projectId: 'maize-beta-6e103',
    authDomain: 'maize-beta-6e103.firebaseapp.com',
    storageBucket: 'maize-beta-6e103.appspot.com',
    measurementId: 'G-DQKCDRX0FY',
  );
}
